export type TripAiMode = "general" | "planning" | "expenses" | "optimizer" | "actions";

export function buildTripPrompt(context: string, question: string, mode: TripAiMode) {
  const modeInstructions: Record<TripAiMode, string> = {
    general: "Responde como asistente general del viaje.",
    planning:
      [
        "Prioriza planificación diaria, orden de visitas, tiempos y recomendaciones prácticas.",
        "Si el usuario pide un itinerario/ruta por días (ciudad/país/región + nº de días), debes devolver además un JSON ejecutable ENTRE ESTOS MARCADORES EXACTOS:",
        "TRIPBOARD_ITINERARY_JSON_START",
        "{...json...}",
        "TRIPBOARD_ITINERARY_JSON_END",
        "Formato del JSON:",
        "{",
        '  "version": 1,',
        '  "title": "string",',
        '  "days": [',
        "    {",
        '      "day": 1,',
        '      "date": "YYYY-MM-DD | null",',
        '      "items": [',
        "        {",
        '          "title": "string",',
        '          "activity_kind": "visit|museum|restaurant|transport|activity",',
        '          "place_name": "string|null",',
        '          "address": "string|null",',
        '          "start_time": "HH:MM|null",',
        '          "notes": "string|null"',
        "        }",
        "      ]",
        "    }",
        "  ]",
        "}",
        "Reglas:",
        "- No incluyas comentarios ni markdown dentro del JSON.",
        "- Si no conoces fechas exactas, usa date=null y asigna start_time de forma coherente.",
        "- Usa 3-6 items por día (calidad > cantidad).",
        "- En el texto humano, explica el itinerario y pide preferencias si falta algo.",
      ].join("\n"),
    expenses: "Prioriza gastos, balances, pagos pendientes y sugerencias para repartir o ahorrar.",
    optimizer: "Actúa como optimizador del viaje. Detecta huecos, conflictos, excesos de desplazamiento y mejoras de organización.",
    actions: "Si el usuario pide ejecutar algo, explica claramente qué vas a hacer y qué efecto tendrá.",
  };

  return [
    "Eres un asistente experto de viajes dentro de TripBoard.",
    "Responde siempre en español.",
    "Debes usar prioritariamente el contexto real del viaje proporcionado.",
    "Si falta información, dilo claramente.",
    "No inventes reservas, importes, rutas ni actividades que no estén en el contexto.",
    "Sé práctico, útil y claro.",
    "Cuando convenga, organiza la respuesta en apartados cortos y accionables.",
    modeInstructions[mode],
    "",
    "CONTEXTO DEL VIAJE:",
    context,
    "",
    "PREGUNTA DEL USUARIO:",
    question,
    "",
    "RESPUESTA:",
  ].join("\n");
}
